const arrayArtists = [{
    id: 1,
    name: 'Amanda',
    age: '29 years',
    experience: '5 years',
    specialt: 'fine line',
    imgPath: './images/artists/AmandaTatuadora.jpg',
    story: '  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequatur adipisci debitis magni quis omnis doloribus sapiente praesentium maiores itaque nostrum veritatis nisi assumenda porro, voluptatum, dolorum ratione libero in. Fugiat.',
    aboutStyle: 'The thin line, or Fineline, is a very popular tattoo style because it fits well anywhere on the body, being quite versatile in terms of the size of the design and the number of objects and scenes possible to represent. With the great advances in the area of ​​materials for tattooing, such as needles and machines, it became possible to make lines more and more precise and thinner, and in the last decades this style of tattoo has won the hearts of many people who previously did not think of having a tattoo because he found the rough features or the designs very striking.',
    styleFeatures: 'Thin lines, precise and often geometric, do not have fill, can be colored or black, but it is quite common to use only the color Black. It is also very common to be applied to small and more minimalist designs. It is the style most sought after by those who want to get their first tattoo.',
    tattoosGalery: [
      './images/fineLine/fineLine1.jpg',
      './images/fineLine/fineLine2.jpg',
      './images/fineLine/fineLine3.jpg',
      './images/fineLine/fineLine4.jpg',
      './images/fineLine/fineLine5.jpg',
    ]
  },{
    id: 2,
    name: 'Cesar',
    age: '32 years',
    experience: '10 years',
    specialt: 'oldSchool',
    imgPath: './images/artists/CesarTatuador.jpg',
    story: '  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequatur adipisci debitis magni quis omnis doloribus sapiente praesentium maiores itaque nostrum veritatis nisi assumenda porro, voluptatum, dolorum ratione libero in. Fugiat.',
    aboutStyle: 'The Old School tattoo is the name of a tattoo style that takes into account Western and traditional features. Because of this, the images are always related to musicians, sailors and barbers.',
    styleFeatures: 'Because it is a more traditional tattoo, the old school has its own characteristics that set it apart from the others. Check out how you can recognize an old school tattoo. Designs that refer to sailors are unique features of the old school tattoo; Old school drawings have black contours, firm and thick lines; The color palette of the old school tattoo is made with strong and striking colors, and the base is formed by the colors yellow, green, blue and red; Most of the time the colors do not mix because when the tattoo style was created there was not much appeal. But today some shades like brown and orange are common.',
    tattoosGalery: [
      './images/oldSchool/oldSchool1.jpg',
      './images/oldSchool/oldSchool2.jpg',
      './images/oldSchool/oldSchool3.jpg',
      './images/oldSchool/oldSchool4.jpg',
      './images/oldSchool/oldSchool5.jpg',
    ]
  },{
    id: 3,
    name: 'Julia',
    age: '25 years',
    experience: '4 years',
    specialt: 'watercolor',
    imgPath: './images/artists/JuliaTatuadora.jpg',
    story: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequatur adipisci debitis magni quis omnis doloribus sapiente praesentium maiores itaque nostrum veritatis nisi assumenda porro, voluptatum, dolorum ratione libero in. Fugiat.',
    aboutStyle: 'The Watercolor style is one of the most popular tattoo styles today. His inspiration came from the painting technique used on paper, which is estimated to have been invented more than 2000 years ago. In tattooing, watercolor appeared around the year 2011, and since then it has become popular all over the world. The designs of this style are fluid and in general have no contours, the colors overlap each other forming the desired image. The transition of colors, from dark to light is one of the dominant effects of this style, as well as the formation of drops of ink "running" on the skin. The watercolor gives a tone of authenticity to each drawing, as the applied effects are unique and the color combination will hardly be reproduced. Tattoos in this style call attention to the way the colors are exposed, as if they were true brush strokes on the skin. What may seem like a simple stain, in fact, is a thorough process for the effect of Aquarela, which arose from the technical evolution of tattoos and has been allowing tattoo artists a new work aesthetic. With that, the tattoo has become much more than an adornment on the skin, but works of art, since in this technique the professional needs to be aware of his observation capacity, because the spots and the fusion of colors are done on the spot, without the possibility of decal, since the result needs to be as real as possible.',
    styleFeatures: 'The main characteristics of this style of filling are vibrant colors and smooth strokes that give movement and fluidity to the design, and the effects of splashes and color transition. Although there is watercolor in shades of black, the most common to observe are the colored ones.',
    tattoosGalery: [
      './images/waterColor/waterColor1.jpg',
      './images/waterColor/waterColor2.jpg',
      './images/waterColor/waterColor3.jpg',
      './images/waterColor/waterColor4.jpg',
      './images/waterColor/waterColor5.jpg',
    ]
  },{
    id: 4,
    name: 'Karen',
    age: '27 years',
    experience: '8 years',
    specialt: 'colorful realism',
    imgPath: './images/artists/KarenTatuadora.jpg',
    story: '  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequatur adipisci debitis magni quis omnis doloribus sapiente praesentium maiores itaque nostrum veritatis nisi assumenda porro, voluptatum, dolorum ratione libero in. Fugiat.',
    aboutStyle: `Realism focuses on reproducing, as faithfully as possible, the scene of a photo on the skin. The great challenge of this tattoo style is to be able to combine the colors used in the tattoo with the skin tone of the person tattooed so that the image is as perfect as possible. Realism within the tattoo is based on the realistic movement started in France in 1850. The focus of this style is the true representation of the image, without romantic tones or adjustments to make the image more dramatic. Contrast and shadow are highly valued in this style. A tattoo in realism can take a few tens of hours to complete, due to the precision of strokes and colors required.`,
    styleFeatures: 'In this category of tattoo images of animals such as lion, tiger, gorilla, bear, wolves, among others are often made. In addition to animals, in colorful realism tattoos of peoples faces and everyday objects are also very common. In black and gray realism, the reproduction of faces and landscapes is very common.',
    tattoosGalery: [
      './images/colorfulRealism/colorfulRealism1.jpg',
      './images/colorfulRealism/colorfulRealism2.jpg',
      './images/colorfulRealism/colorfulRealism3.jpg',
      './images/colorfulRealism/colorfulRealism4.jpg',
      './images/colorfulRealism/colorfulRealism5.jpg',
    ]
  },{
    id: 5,
    name: 'Kleber',
    age: '28 years',
    experience: '8 years',
    specialt: 'new traditional',
    imgPath: './images/artists/KleberTatuador.jpg',
    story: '  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequatur adipisci debitis magni quis omnis doloribus sapiente praesentium maiores itaque nostrum veritatis nisi assumenda porro, voluptatum, dolorum ratione libero in. Fugiat.',
    aboutStyle: `Neo Tradicional is a very new style in the tattoo scene, and it is increasingly gaining space especially among color lovers. Mixing Old School and New School, a new era is born. In Europe, in 2008, what we call Neo Traditional or New Traditional appears. As it is a very recent trend, we understand that the Neo Traditional era is still writing its history through current artists. What we can say is that there is a great mix between the typical Old School designs, such as swallows, hearts, eagles, anchors etc., and the unlimited color palette of the New School.`,
    styleFeatures: 'Finer contours, mix of colors, transition between colors, more faithful images to the real world and shading, are among the main characteristics of the style. Among the most common designs are female faces, animals, Native American culture and mythology in general.',
    tattoosGalery: [
      './images/newTraditional/newTraditional1.jpg',
      './images/newTraditional/newTraditional2.jpg',
      './images/newTraditional/newTraditional3.jpg',
      './images/newTraditional/newTraditional4.jpg',
      './images/newTraditional/newTraditional5.jpg',
    ]
  },{
    id: 6,
    name: 'Sergio',
    age: '26 years',
    experience: '7 years',
    specialt: 'lettering',
    imgPath: './images/artists/SergioTatuador.jpg',
    story: '  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequatur adipisci debitis magni quis omnis doloribus sapiente praesentium maiores itaque nostrum veritatis nisi assumenda porro, voluptatum, dolorum ratione libero in. Fugiat.',
    aboutStyle: `Lettering is the art of creating new letter fonts, that is, this style runs away from existing fonts and creates a new representation for words and phrases, being able to form new designs and patterns. Every Lettering is a written word, number or phrase, but not all writing is Lettering, because in judgments of this style of tattoo, the authenticity of the created font is taken into account, that is, a phrase written with a font that exists on a computer it is not authentic enough to win a prize. But outside the world of tattoo conventions it is possible to encompass all tattoos written in that same style.`,
    styleFeatures: 'They always represent words, numbers or phrases, they can have extremely thin and fluid lines, but they can also count many details, among them shading, negative space, filling and volume.',
    tattoosGalery: [
      './images/lettering/lettering1.jpg',
      './images/lettering/lettering2.jpg',
      './images/lettering/lettering3.jpg',
      './images/lettering/lettering4.jpg',
      './images/lettering/lettering5.jpg',
    ]
  },
]
export default arrayArtists
